# kafka-test-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-test-script
data:
  kafka-test.js: |
    import { Writer } from 'k6/x/kafka';
    import { check } from 'k6';

    export let options = {
      vus: 5,
      duration: '2m',
    };

    export default function() {
      const writer = new Writer({
        brokers: ['kafka-cluster-kafka-brokers:9092'],
        topic: 'test-topic',
        autoCreateTopic: true,
      });

      try {
        writer.produce({
          messages: [
            {
              value: `Test message ${__VU}-${__ITER}`,
            },
          ],
        });

        check(writer, {
          'mensagem enviada': () => true,
        });
      } catch (error) {
        console.log('Erro ao enviar:', error);
      }

      writer.close();
    }
