# kafka-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka1
  namespace: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    name: external
  - port: 19092
    targetPort: 19092
    name: internal
  - port: 29092
    targetPort: 29092
    name: client
  - port: 9999
    targetPort: 9999
    name: jmx
  selector:
    app: kafka
