# zookeeper-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zoo1
  namespace: kafka-cluster
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  ports:
  - port: 2181
    targetPort: 2181
    name: client
  - port: 2888
    targetPort: 2888
    name: follower
  - port: 3888
    targetPort: 3888
    name: election
  selector:
    app: zookeeper
