# zookeeper-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  namespace: kafka-cluster
data:
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_SERVER_ID: "1"
  ZOOKEEPER_SERVERS: "0.0.0.0:2888:3888"
